<?php
namespace ns\example;
use eftec\minilang\MiniLang;

/**
* This class has the motor and definitions of the Mini Language.
*.
* @package ns\example.
* @generated by https://github.com/EFTEC/MiniLang.
* @version 2.20.2 2021-10-02T22:09:33-03:00.
*/
class ExampleBasicClass extends MiniLang {
	public $numCode=3; // num of lines of code 
	public $usingClass=true; // if true then we are using a class (this class) 
	public function whereRun($lineCode=0) {
		switch($lineCode) {
			case 0:
			case 2:
			case 3:
				return true; // nothing to do
			case 1:
				$result=$this->dict['var1']=='hello' && $this->dict['comp']['f']==$this->callFunction('false',[]);
				break;
			default:
				$result=false;
				$this->throwError('Line '.$lineCode.' is not defined');
		}
		return $result;
	} // end function WhereRun
	public function loopRun($lineCode=0) {
		switch($lineCode) {
			case 0:
				$result=['a1',$this->dict['values']];
				break;
			case 1:
				$result=null;
				break;
			case 2:
				$result=null;
				break;
			case 3:
				$result=['end',null];
				break;
			default:
				$result=null;
				$this->throwError('Line '.$lineCode.' is not defined');
		}
		return $result;
	} // end function loopRun
	public function setRun($lineCode=0) {
		switch($lineCode) {
			case 0:
			case 3:
				break; // nothing to do
			case 1:
				$this->dict['var2']='world';
				$this->dict['counter']=$this->dict['counter']+1;
				break;
			case 2:
				$this->dict['var3']='world2';
				break;
			default:
				$this->throwError('Line '.$lineCode.' is not defined for set');
		}
	} // end function setRun
	public function elseRun($lineCode=0) {
		switch($lineCode) {
			case 0:
			case 1:
			case 2:
			case 3:
				break; // nothing to do
			default:
				$this->throwError('Line '.$lineCode.' is not defined for else');
		}
	} // end function elseRun
	public function initRun($lineCode=0) {
		switch($lineCode) {
			case 0:
			case 1:
			case 2:
			case 3:
				break; // nothing to do
			default:
				$this->throwError('Line '.$lineCode.' is not defined for init');
		}
	} // end function initRun
} // end class
