<?php
namespace ns\example;
use eftec\minilang\MiniLang;

/**
* This class has the motor and definitions of the Mini Language.
*.
* @package ns\example.
* @generated by https://github.com/EFTEC/MiniLang.
* @version  2.18. 2021-09-26T18:30:48-03:00.
*/
class ExampleBasicClass extends MiniLang {
	public $numCode=2; // num of lines of code 
	public $usingClass=true; // if true then we are using a class (this class) 
	public function whereRun($lineCode=0) {
		switch($lineCode) {
			case 0:
				$result=$this->dict['var1']=='hello' && $this->dict['comp']['f']==$this->callFunction('false',[]);
				break;
			case 1:
				$result=true;
				break;
			default:
				$result=false;
				$this->throwError('Line '.$lineCode.' is not defined');
		}
		return $result;
	} // end function WhereRun
	public function setRun($lineCode=0) {
		switch($lineCode) {
			case 0:
				$this->dict['var2']='world';
				break;
			case 1:
				$this->dict['var3']='world2';
				break;
			default:
				$this->throwError('Line '.$lineCode.' is not defined');
		}
	} // end function SetRun
	public function elseRun($lineCode=0) {
		switch($lineCode) {
			case 0:
				break;
			case 1:
				break;
			default:
				$this->throwError('Line '.$lineCode.' is not defined');
		}
	} // end function ElseRun
	public function initRun($lineCode=0) {
		switch($lineCode) {
			case 0:
				break;
			case 1:
				break;
			default:
				$this->throwError('Line '.$lineCode.' is not defined');
		}
	} // end function InitRun
} // end class
