<?php
use eftec\minilang\MiniLang;

/**
* This class has the motor and definitions of the Mini Language.
*.
* @package .
* @generated by https://github.com/EFTEC/MiniLang.
* @version  2.18. 2021-09-26T18:31:09-03:00.
*/
class ExampleBasicClass2 extends MiniLang {
	public $numCode=4; // num of lines of code 
	public $usingClass=true; // if true then we are using a class (this class) 
	public function whereRun($lineCode=0) {
		switch($lineCode) {
			case 0:
				$result=$this->dict['field1']['id']>0 && $this->dict['field1']['id']<10;
				break;
			case 1:
				$result=$this->dict['field1']['id']>=10 && $this->dict['field1']['id']<20;
				break;
			case 2:
				$result=$this->dict['field1']['id']>=20 && $this->dict['field1']['id']<30;
				break;
			case 3:
				$result=true;
				break;
			default:
				$result=false;
				$this->throwError('Line '.$lineCode.' is not defined');
		}
		return $result;
	} // end function WhereRun
	public function setRun($lineCode=0) {
		switch($lineCode) {
			case 0:
				$this->dict['field2']['value']=$this->callFunction('param',[$GLOBALS['a'],'a.b.c']);
				$this->callFunction('processcaller',[$this->dict['field3']]);
				$this->callFunction('processservice',[$this->dict['field3']]);
				break;
			case 1:
				$this->dict['field2']['value']=$this->callFunction('param',[$GLOBALS['a'],'a.b.c']);
				$this->callFunction('processcaller',[$this->dict['field3']]);
				$this->callFunction('processservice',[$this->dict['field3']]);
				break;
			case 2:
				$this->dict['field2']['value']=$this->callFunction('param',[$GLOBALS['a'],'a.b.c']);
				$this->callFunction('processcaller',[$this->dict['field3']]);
				$this->callFunction('processservice',[$this->dict['field3']]);
				break;
			case 3:
				$this->dict['field2']['value']=$this->callFunction('param',[$GLOBALS['a'],'a.b.c']);
				$this->callFunction('processcaller',[$this->dict['field3']]);
				$this->callFunction('processservice',[$this->dict['field3']]);
				break;
			default:
				$this->throwError('Line '.$lineCode.' is not defined');
		}
	} // end function SetRun
	public function elseRun($lineCode=0) {
		switch($lineCode) {
			case 0:
				break;
			case 1:
				break;
			case 2:
				break;
			case 3:
				break;
			default:
				$this->throwError('Line '.$lineCode.' is not defined');
		}
	} // end function ElseRun
	public function initRun($lineCode=0) {
		switch($lineCode) {
			case 0:
				break;
			case 1:
				break;
			case 2:
				break;
			case 3:
				break;
			default:
				$this->throwError('Line '.$lineCode.' is not defined');
		}
	} // end function InitRun
} // end class
